branches:
  only:
  - master
  - development
language: python
notifications:
  email: false
python:
- '3.7'
install:
- pip install -r requirements.txt
before_script:  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: coverage run --rcfile=.coveragerc -m unittest discover
after_script: 
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then ./cc-test-reporter after-build -t coverage.py -p ./coverage.xml --exit-code $TRAVIS_TEST_RESULT; fi