'''
Uses the eigenvalues file generated by Octopus and makes its information
available to use

Information contained in bandstructure file
-------------------------------------------
eigenvalues -> occupation, number of occupied bands
'''

import numpy as np

class Eigenvalues():
    '''
    Class that holds and gives methods to the information of an eigenvalues
    file

    Attributes:
      _eigenvalues (list string): holds all the data of the eigenvalues file in a list
      _eigenvalues_path (string): filepath with the addition of the eigenvalues file
      _num_bands (int): number of bands
      _num_kpoints (int): number of kpoints
      num_occ_bands (int): number of occupied bands
      occupancies (numpy array): of shape (num_kpoints, num_bands) type (float64)
    '''

    def __init__(self, filepath, num_kpoints, num_bands):
        '''
        Args:
          filepath (string): filepath to find eigenvalues file
          num_kpoints (int): number of kpoints
          num_bands (int): number of bands
        '''
        
        self._eigenvalues = None
        self._eigenvalues_path = filepath + 'eigenvalues'
        self._num_bands = num_bands
        self._num_kpoints = num_kpoints
        self.num_occ_bands = None
        self.occupancies = None
        self._load_eigenvalues()


    def get_occupancies(self):
        '''
        Extracts the occupancies from the eigenvalue data

        Returns:
          occupancies (numpy array): of shape (num_kpoints, num_bands) type (float64)
        '''

        # find the index of the match and get numkpoints of lines results
        match = ' #st  Spin   Eigenvalue      Occupation     Error'
        start = self._eigenvalues.index(match)

        # start at the second line not including the matched text
        eigenvalues_table = self._eigenvalues[start:][1:]

        # remove the kpoint lines
        eigenvalues_table = [value for value in eigenvalues_table if '#k' not in value]

        # place the occupancies into a numpy array
        occupancy_list = [row.split()[3] for row in eigenvalues_table]
        occupancies = np.array(occupancy_list)

        # change to shape (num_kpoints, num_bands)
        occupancies.shape = (self._num_kpoints, self._num_bands)
        self.occupancies = occupancies.astype('float64')

        return(self.occupancies)

    def get_num_occ_bands(self):
        '''
        Extracts the number of occupied bands from the occupancy array
        
        Returns:
          num_occ_bands (int): Number of occupied bands
        '''

        # any nonzero occupancy is considered occupied
        num_occ_bands = np.count_nonzero(self.occupancies[0])
        self.num_occ_bands = num_occ_bands
        return(self.num_occ_bands)

    def _load_eigenvalues(self):
        '''
        Loads the eigenvalues file as a list of lines

        Returns:
          eigenvalues (list string): list of lines from eigenvalues
        '''

        f = open(self._eigenvalues_path, 'r')
        text = f.read()

        # creates a list of lines rather than a long string with newline characters
        self._eigenvalues = text.splitlines()
        f.close()